### ISSUE TITLE
"Token renewal operation failed due to timeout" for app hosted at another Azure AD

### ISSUE THREAD

**Issue by leniel** [AzureAD/microsoft-authentication-library-for-js#1091]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ X ] Other... Please describe:
</code></pre>

## Browser:
- [ X ] Chrome version 78.0.3904.70 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
<pre><code>
Library version: MSAL 1.1.3 and MSAL AngularJS latest wrapper
</code></pre>

## Current behavior
I have a custom Keep Me Signed In [KMSI] Azure AD B2C policy with the following Technical profile for testing purposes:

```
<TechnicalProfiles>
        <TechnicalProfile Id="JwtIssuer">
          <Metadata>
            <Item Key="token_lifetime_secs">600</Item>
            <!-- 10 minutes -->
            <Item Key="id_token_lifetime_secs">600</Item>
            <!-- 10 minutes -->
            <Item Key="refresh_token_lifetime_secs">1209600</Item>
            <!-- 14 days -->
            <Item Key="rolling_refresh_token_lifetime_secs">7776000</Item>
            <!-- 90 days -->
            <Item Key="IssuanceClaimPattern">AuthorityAndTenantGuid</Item>
            <Item Key="AuthenticationContextReferenceClaimPattern">None</Item>
          </Metadata>
        </TechnicalProfile>
```

Single Sign On is configured like this:

```
<UserJourneyBehaviors>
      <SingleSignOn Scope="Application" KeepAliveInDays="2" />
      <SessionExpiryType>Rolling</SessionExpiryType>
      <!-- The Rolling value (default) indicates that the user remains signed in as long as the user is continually active in the application. -->
      <SessionExpiryInSeconds>1800</SessionExpiryInSeconds>
      <!-- 30 minutes -->
. . .
```

## Expected behavior

With KMSI check box checkmarked...

When debugging locally that is: https://localhost:49707/ I can see that the token is being renewed automatically right before being expired. I copy the bearer token from Google Dev Tools and paste it @ https://jwt.io/. "exp" and  "nbf" are being moved forward and the user can keep working as long as they're active. This is the expected behavior.

The problem is that the same deployed application hosted at https://myapp.azurewebsites.net (Azure App service in a different Azure AD), is not renewing the token. Right before the time to renew the token the user gets redirected to the login\sign page again.

Would this be related to the application being hosted in a different Azure AD than the B2C one?

What could be causing token renewal not happening?

**Comment by pkanher617** [comment]
Hi @leniel, if I understand you correctly, you are seeing a different behavior in the AAD tenant than the B2C tenant in terms of token renewal, correct? Does this error come back as the "Token renewal operation failed due to timeout" error in the title? If so, we are working on fixing part of this issue. When we create an iframe for token renewal, we check whether a fragment comes back in the url. However, sometimes this error doesn't come back in the fragment, since we aren't defaulting our response mode to fragment. This is fixed in a PR, and we are investigating other issues that can cause this.

This bug may be masking the actual issue preventing token renewal, because we don't detect the issue from the server coming back. So once we roll this fix out, I can't necessarily say it will fix the issue stopping your token renewal, but it will at least be more informative about the error you are receiving from the Azure AD hosting the https://myapp.azurewebsites.net application. PR #1090 is the first step to fix this, and it has been merged, so you can try pulling dev and seeing if the token renewal timeout error is still occurring.

**Comment by leniel** [comment]
Hey @pkanher617 thanks for the reply.

Yep, you're correct. The error comes out as **Token renewal operation failed due to timeout**.

The **id_token** token gets renewed locally when debugging in my machine, that is, the app is not hosted in the Azure app service. When debugging locally I interact only with the Azure AD B2C.

However when debugging the live app that is hosted in a different Azure AD (B2B) [ _not the B2C one where the **id_token** is being generated_ ], token renewal does not happen and the following method is called:

````
$rootScope.$on("msal:acquireTokenFailure", function (event, errorDesc, error)
{
    console.log("acquireTokenFailure:\n" + error + " - " + errorDesc);

    //debugger;

    //acquireTokenSilently();

    msalService.loginRedirect();
});
```

I'll give the dev branch a try... maybe it'll fix this problem.

**Comment by leniel** [comment]
@pkanher617 downloaded the project and built it using Visual Studio code. Updated msal and deployed it to the azure app service. I'm using this version `msal v1.2.0-beta.2 `.

I'm still getting `Token renewal operation failed due to timeout` when the token expires.

Note that **Keep Me Signed In** marked during login. I'm testing with 10 minutes expire time (600 seconds). This is set in `token_lifetime_secs` and `id_token_lifetime_secs`. So it should renew the token automatically, before the 10 minutes mark, correct?

Locally on my machine it renews the token just fine and the token properties [exp and nbf] are updated accordingly. The user gets 10 minutes more to browse the application.

![image](https://user-images.githubusercontent.com/764854/68138990-265d9800-ff08-11e9-99e5-368260db1743.png)

**Comment by pkanher617** [comment]
@leniel Sorry for the delay. Could you please post a snippet of the code that you are using to acquire a token?

> Would this be related to the application being hosted in a different Azure AD than the B2C one?

> The id_token gets renewed locally when debugging in my machine, that is, the app is not hosted in the Azure app service. When debugging locally I interact only with the Azure AD B2C.
> 
> However when debugging the live app that is hosted in a different Azure AD (B2B) [ not the B2C one where the id_token is being generated ], token renewal does not happen and the following method is called
I believe what is happening here is that within the hidden iframe there is some sort of error page being displayed that MSAL isn't detecting. This propogates as a timeout error since we expect this to return a token or error in the hash, rather than a displayed error page.

I'm a little confused by what the authentication model is. Correct me if I'm wrong:
You are attempting to allow users from an Azure AD B2C tenant (Tenant A) to sign in to another organzational Azure AD tenant (Tenant B, hosting the application https://myapp.azurewebsites.net) using Azure AD B2C. This is why you would like to sign in a user at Tenant A, then renew this token at tenant B without user interaction.

**Comment by leniel** [comment]
Hey @pkanher617 thanks for your attention to this ticket. I also have this other one open https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1124 see if you can shed some light there... 👍 

Regarding this ticket: the application is hosted in another Azure AD tenant (Tenant B) at  https://myapp.azurewebsites.net... this application in tenant B is configured to authenticate users from Azure AD B2C (Tenant A). As I described in the issue it's using MSAL + AngularJS wrapper.

**This is why you would like to sign in a user at Tenant A, then renew this token at tenant B without user interaction.** Exactly this

I thought the token would renew automatically as it happens on my machine when I debug locally.

The Angular app configuration as of now is like this:

```
// #region MSAL

    // MSAL - Microsoft Authentication Library (MSAL) for Angular JS
    // https://github.com/AzureAD/microsoft-authentication-library-for-js
    // https://www.npmjs.com/package/@azure/msal-angularjs
    theApp.config(['$httpProvider', 'msalAuthenticationServiceProvider', 'AADB2C', function ($httpProvider, msalProvider, AADB2C)
    {
        window.msalAppConfig = {
            clientID: AADB2C[location.host].CLIENT_ID,
            authority: AADB2C[location.host].AUTHORITY,
            tokenReceivedCallback: msalCallback,
            optionalParams: {
                unprotectedResources: ["/ng/views/directives/system/footer.html","/ng/views/system/login.html"],
                navigateToLoginRequestUrl: false,
                validateAuthority: false, // https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin,
                cacheLocation: 'sessionStorage',
                storeAuthStateInCookie: true
            }
        };
```

AngularJS service which call `loginRedirect`:

```
APPFactory.login = function ()
            {
                localStorageService.clearAll();
                
                msalService.loginRedirect();
            };

            ASFactory.logout = function ()
            {
                localStorageService.clearAll();

                msalService.logout();
            };
```

**Comment by pkanher617** [comment]
@leniel I believe the reason the dev branch update didn't work is because the angularjs package is currently locked to MSAL core 0.2.2 version, so it will not have the latest updates for MSAL core. Unfortunately, MSAL AngularJS is currently in maintenance mode, and we aren't planning any major work on the library. 

Could you please try using the latest alpha in the MSAL Angular package? This alpha has recently updated the usage to use the latest versions of the MSAL library and may give you better user experience and error reporting.

You should also make sure your app registrations are following the multi-tenanted model [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-setup-commonaad-custom?tabs=applications).

**Comment by jasonnutter** [comment]
Alpha of MSAL Angular: `@azure/msal-angular@1.0.0-alpha.0`. Requires `msal@1.2.0` as a peer dependency.

**Comment by tnorling** [comment]
Closing due to inactivity. Let us know if this is still an issue with msal-angular.
