### ISSUE TITLE
Azure B2C returning Status 400 (Bad request) when clicking Sign in button after tab is left open from night to day in the Login screen

### ISSUE THREAD

**Issue by leniel** [AzureAD/microsoft-authentication-library-for-js#1124]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ X ] Other... Please describe:
</code></pre>

## Browser:
- [ X ] Chrome version 78.0.3904.108
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ X ] Safari version  13.0.3 (15608.3.10.1.4)

## Library version

<pre><code>
Library version: msal v1.2.0-beta.2 2019-11-04
</code></pre>

## Current behavior
This error is being really difficult to debug.

The application is an AngularJS one (SPA) in the front-end with ASP.NET MVC back-end. In the front-end we're using MSAL JS + MSAL JS AngularJS wrapper.

The problem appears when a browser tab is left open in the login screen for let's say from night to next day.

When clicking the Sign in button the next day, the page starts loading and then stops still in the login screen. Opening Chrome Dev Tools I see a call like this in the Network pane with Status = 400 (Bad request):

`https://tenant.b2clogin.com/77777777-7bd7-777e-7a7e-ba7ff777f77c/B2C_1A_SignInOnlyKMSI/SelfAsserted?tx=StateProperties=eyJUSUQiOiI5NjNiYzhkNS04N2M1LTQyYmUtOGIzZC1mYjk5MWQ0MmRmNjUifQ&p=B2C_1A_SignInOnlyKMSI`

In the address bar the URL is this:

`https://tenant.b2clogin.com/77777777-7bd7-777e-7a7e-ba7ff777f77c/b2c_1a_signinonlykmsi/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=e7777777-e7fb-70b7-ba77-7777b7b7d77d&redirect_uri=https%3A%2F%2Fwebsite.azurewebsites.net%2F&state=5b7c6712-56d5-41fb-bbf2-de2a22bb4ada&nonce=7b7622e0-0e72-4429-bbe3-5cb5c538c60c&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.2&client-request-id=6995a8ee-d57a-4373-9005-b34cce6bc21d&prompt=select_account&response_mode=fragment`

![image](https://user-images.githubusercontent.com/764854/69245292-5605d480-0b85-11ea-9526-dc2973b66eaf.png)

How to really know what's causing this Status = 400? Is there any approach I can to take to debug this error?

Note: if I refresh the page and click the Sign in button, everything works as expected.

I suspect somehow something is getting expired behind the curtains.

We're using a custom B2C policy called b2c_1a_signinonlykmsi.

## Expected behavior
When clicking the Sign in button the next day it should just work as expected, that is, the user is logged in successfully.

## Failed XHR request Summary\Headers

* replaced tenant name, tenant id, application id, etc with fake values.

> https://ourb2c.b2clogin.com/TENANTID/B2C_1A_SignInOnlyKMSI/SelfAsserted?tx=StateProperties=eyJUSUQiOiJlZWViODg2OC0zZGU2LTRlZTUtOTVkMS1kNjFiYzRiNDYyZjEifQ&p=B2C_1A_SignInOnlyKMSI

```
Summary
URL: https://ourb2c.b2clogin.com/TENANTID/B2C_1A_SignInOnlyKMSI/SelfAsserted?tx=StateProperties=eyJUSUQiOiJlZWViODg2OC0zZGU2LTRlZTUtOTVkMS1kNjFiYzRiNDYyZjEifQ&p=B2C_1A_SignInOnlyKMSI
Status: 400 Bad Request
Source: Network
Address: 40.126.17.39:443
Initiator: 
jquery-bundle-1.10.2.min.js:3:85424


Request
POST /TENANTID/B2C_1A_SignInOnlyKMSI/SelfAsserted HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-us
Accept-Encoding: gzip, deflate, br
Host: ourb2c.b2clogin.com
Origin: https://ourb2c.b2clogin.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Referer: https://ourb2c.b2clogin.com/TENANTID/b2c_1a_signinonlykmsi/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=e7777777-e7fb-70b7-ba77-7777b7b7d77dd&redirect_uri=https%3A%2F%2Fcipodev3.azurewebsites.net%2F&state=1e63af9d-d551-40db-b610-7c3c4cbab4e3&nonce=a8ab9881-b25d-4d11-b24a-ec9fe9083508&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.2&client-request-id=1ad07362-bf91-4380-bc34-e113a191a6c5&prompt=select_account&response_mode=fragment
Content-Length: 69
Connection: keep-alive
Cookie: x-ms-cpim-cache:aijr7uy95u6v0dybxlri8q_0=m1.AtOTpcEx0oiNIlol.3FcXJdTGaN43vXPnPghlLA==.0.VGBsytOmN+B8MaXmR81yda3u3c/dn/sAUyftdQfYpRM34MvOYxzCWYCehCZQW69Y/ZGLFO6a9JdUznEIkrj+VZsq+hBT+xlTcWW48eAc0a/8kSuDB1Ct2oOwFsxBNzwXw5Jfra1LasjY2qXLB93iRT5bQAAmsIoNcIjUTiDbQGwkIHD7HB4DOgNRzRAAsynQrf57sb6CM7uetXYpq3ENtXUcIQouvJKTRXLrXpV1nF3HGpkP7Phd0CzsORjnbKkOCOI4l4xH0Ul/R/tHCzJBwvQ5i7nNWS63VBEszW8FB47ZdX4Wfg70GN0fms12LJ4uOfxPLe8G6mONgBMAr+vuAJVH11ctQref/64t5L5fmPkX+wV5LWWwX44lgexsvR0ggxMqhbxZe6kaTt9MsfKsbEGd5QSTwJrYij0c3ELQnIJbAQ/cQzQP0BnO1MzCt8IrjocrrlrAN8X9TTnmlf4wxcbzCtMZ8AG/kO4eHI5OywtLxsw8rlJJBd6UfxrNoNLDbjhW/svkiVoocaqPLpmOdfxlDNaeOX579Z3PV5eMmXG5AvvOFdJFFBX6MqlrQWpKdY22zbwFdD+ZxO4pGtWxNA/2Ux6itF/LMw1+37zAmBrU/gJ3Hc2tFf3Jo0hkTnZTDEz01eb6q5QoTeHKF89H94SdaH4Pww/PO+5IKUT30scdzvb1Adpa7v5qs+UyqF3qhwPH763L8qgjGQL0VBNiptKSpkxdZhPIfgn0LZB2e0oU; x-ms-cpim-csrf=QzVTTWFqckR5K00xTHh5b2pEbkFmMUlYWVluZEJNUm0vM2VzUkljaS9FNnh6TUZPN0VTeEN1NDFNdGtDSmZ2d0dTVWV5YkRUNXRGN2tiSndGbHIrd2c9PTsyMDE5LTExLTIxVDE1OjQyOjQ1LjA4MTIyNDFaO3FIYjVnK2ZKOVdjbkk3WHJzdTNMclE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoxfQ==; x-ms-cpim-trans=eyJUX0RJQyI6W3siSSI6ImVlZWI4ODY4LTNkZTYtNGVlNS05NWQxLWQ2MWJjNGI0NjJmMSIsIlQiOiJjaXBvYjJjLm9ubWljcm9zb2Z0LmNvbSIsIlAiOiJiMmNfMWFfc2lnbmlub25seWttc2kiLCJDIjoiZTAyMTUyNDAtZTJmYi00MGIyLWJhMDctODc4NmIwYjVkMTVkIiwiUyI6MSwiTSI6e30sIkQiOjB9XSwiQ19JRCI6ImVlZWI4ODY4LTNkZTYtNGVlNS05NWQxLWQ2MWJjNGI0NjJmMSJ9
X-Requested-With: XMLHttpRequest
X-CSRF-TOKEN: QzVTTWFqckR5K00xTHh5b2pEbkFmMUlYWVluZEJNUm0vM2VzUkljaS9FNnh6TUZPN0VTeEN1NDFNdGtDSmZ2d0dTVWV5YkRUNXRGN2tiSndGbHIrd2c9PTsyMDE5LTExLTIxVDE1OjQyOjQ1LjA4MTIyNDFaO3FIYjVnK2ZKOVdjbkk3WHJzdTNMclE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoxfQ==

Response
HTTP/1.1 400 Bad Request
X-Content-Type-Options: nosniff
Content-Type: text/html
Date: Fri, 22 Nov 2019 18:51:46 GMT
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Content-Length: 11
Cache-Control: private
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-gateway-requestid: 2da383ca-f039-4412-9327-11553427a1bb

Query String Parameters
tx: StateProperties=eyJUSUQiOiJlZWViODg2OC0zZGU2LTRlZTUtOTVkMS1kNjFiYzRiNDYyZjEifQ
p: B2C_1A_SignInOnlyKMSI

Request Data
MIME Type: application/x-www-form-urlencoded; charset=UTF-8
request_type: RESPONSE
signInName: user@gmail.com
password: Password
```

**Comment by jmckennon** [comment]
@leniel My initial thought is that a token is expiring in there somewhere, can you give us some more information?

Is the only time you're seeing this functionality when you wait for some period of time after opening the page? Can you try to determine how long you have to wait for this to happen, and maybe provide timestamps?

**Comment by jmckennon** [comment]
Can you also try upgrading to `v1.2.0-beta.4`? We fixed a bunch of bugs in `.4`, and while this may be unrelated, it's worth a shot.

**Comment by leniel** [comment]
@jmckennon yep... this only happens when waiting for some period of time after opening the login page. I didn't calculate how long it takes to fail.

I'm testing the latest version https://www.npmjs.com/package/msal/v/1.2.0-beta.4.

Let's see what happens.

**Comment by jmckennon** [comment]
Yeah, let us know if you see a change in behavior on the new build.

I don't know if there's any _easy_ way to automate it, but my thoughts were more to look at common expiry times, like 1 hour, 2 hours, 6 hours, etc. We also may just need to escalate this on to B2C.

**Comment by leniel** [comment]
Updating to  `1.2.0-beta.4` did not solve the problem.

I wrote a simple test using[ puppeteer](https://github.com/puppeteer/puppeteer).

Looks like it stops working after 6 hours. See the printscreen:

![image](https://user-images.githubusercontent.com/764854/69423614-4f05d000-0d05-11ea-951a-4b93b3d60625.png)

Any idea where I should look at?

**Comment by jmckennon** [comment]
The default expiry time for our tokens is 1 hour, so it would make sense that a token is likely expiring. You should be calling `acquireTokenSilent` right before making an API call (e.g. when the sign in button is clicked here) that requires an access token, and MSAL will figure out if one is needed. Is that currently the case in your app? My guess is that a token is likely being acquired on page load, and then 1 hour later expires, giving you this bad request.

**Comment by leniel** [comment]
We're just  using the `id_token`. There's no access token involved.

I left a new improved test running today... tomorrow I should have better details.

**Comment by sameerag** [comment]
Any token: `access_token` or `id_token` expires after an hour but as long as you have an AAD session, you should be able to get the token renewed silently by calling `acquireTokenSilent`. Are you doing the same?

**Comment by leniel** [comment]
Left a new test running and got this after 1 hour:

`(node:55477) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.`

@sameerag: what I don't understand is that the login page doesn't need a token.

The angularJS app has the following config:

```
window.msalAppConfig = {
    clientID: AADB2C[location.host].CLIENT_ID,
    authority: AADB2C[location.host].AUTHORITY,
    tokenReceivedCallback: msalCallback,
    optionalParams: {
        unprotectedResources: ["/ng/views/directives/system/footer.html"],
        navigateToLoginRequestUrl: false,
        validateAuthority: false, // https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin,
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: true,
        //logger: loggerCallback
    }
};
```

When the app's login.html page is called we do this:

```
// This triggers the login button automatically to call Azure B2C Sign In policy. It's used to bypass the login page that is only used to setup MSAL context.
// login.html page is necessary because MSAL needs to create context (register a callback) before redirecting to Azure B2C Sign In policy. The callback will receive the response from Azure B2C policy.
$timeout(function ()
{
    angular.element('#login-button').triggerHandler('click');
}, 0);
```

The button click calls `msalService.loginRedirect()` that redirects to our custom B2C login page shown in this question (we use a custom policy based on the default template provided by Microsoft):

```
login = function ()
{
    localStorageService.clearAll();
    
    msalService.loginRedirect();
};
```

What do you see is wrong? Why should I call `acquireTokenSilent`? Shouldn't it happen automatically?

**Comment by leniel** [comment]
I'm re-testing after adding the `login.html` page to the `unprotectedResources` parameter. Maybe that could be the issue.

`unprotectedResources: ["/ng/views/directives/system/footer.html","/ng/views/system/login.html"]`

**Comment by leniel** [comment]
So far this seems to be effective:

`
Leniels-MacBook-Pro:src leniel$ ts-node run
Started 3 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 12 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 3.5 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 5 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 4 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 8 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 9 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 1 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 7 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 4.5 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 1.5 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 6 hour(s) test on: November 23rd 2019, 1:09:53 pm.
Started 11 hour(s) test on: November 23rd 2019, 1:09:54 pm.
Started 2 hour(s) test on: November 23rd 2019, 1:09:54 pm.
Started 2.5 hour(s) test on: November 23rd 2019, 1:09:54 pm.
Started 0.016666666666666666 hour(s) test on: November 23rd 2019, 1:09:54 pm.
Started 10 hour(s) test on: November 23rd 2019, 1:09:54 pm.
Waiting for 60 minutes...
Waiting for 360 minutes...
Waiting for 480 minutes...
Waiting for 210 minutes...
Waiting for 150 minutes...
Waiting for 180 minutes...
Waiting for 420 minutes...
Waiting for 660 minutes...
Waiting for 300 minutes...
Waiting for 540 minutes...
Waiting for 270 minutes...
Waiting for 120 minutes...
Waiting for 90 minutes...
Waiting for 720 minutes...
Waiting for 600 minutes...
Waiting for 240 minutes...
Waiting for 1 minutes...
Clicked Sign in button for 1 minutes test.
Bearer token for 1 minutes test
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6I..........
Clicked Sign in button for 60 minutes test.
Bearer token for 60 minutes test
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6I..........
Clicked Sign in button for 90 minutes test.
Bearer token for 90 minutes test
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6I..........
Clicked Sign in button for 120 minutes test.
Bearer token for 120 minutes test
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6I..........
`

**Comment by sameerag** [comment]
Our documentation says the below:

**unprotectedResources** : Array of URI's. Msal will not attach a token to outgoing requests that have these uri. Defaults to 'null'.

**protectedResourceMap** : Mapping of resources to scopes {"https://graph.microsoft.com/v1.0/me", ["user.read", "mail.send"]}. Used internally by the MSAL for automatically attaching tokens in webApi calls. This is required only for CORS calls.

It is possible that placing a loginCall in `protectedResources` is mandating token validity in your use case. Closing this issue as you seem to have a working solution. Please reopen if you believe you need more help.

**Comment by leniel** [comment]
@sameerag in a new test, the login page stopped working after the page is idle for more than 4 hours... see the complete test result...

```
Clicked Sign in button for 5.00 hour(s) test
Failed during test for 5.00 hour(s).
Time elapsed in minutes: 300
TimeoutError: Navigation timeout of 30000 ms
```

This is the SignInPolicy token configuration:

```
<ClaimsProvider>
  <DisplayName>Token Issuer</DisplayName>
  <TechnicalProfiles>
    <TechnicalProfile Id="JwtIssuer">
      <Metadata>
        <Item Key="token_lifetime_secs">604800</Item>            <!-- 1 week -->
        <Item Key="id_token_lifetime_secs">604800</Item>            <!-- 1 week -->
        <Item Key="refresh_token_lifetime_secs">1209600</Item>            <!-- 14 days -->
        <Item Key="rolling_refresh_token_lifetime_secs">7776000</Item>            <!-- 90 days -->
        <Item Key="IssuanceClaimPattern">AuthorityAndTenantGuid</Item>
        <Item Key="AuthenticationContextReferenceClaimPattern">None</Item>
      </Metadata>
    </TechnicalProfile>
  </TechnicalProfiles>
</ClaimsProvider>
```

```
<UserJourneyBehaviors>
      <SingleSignOn Scope="Application" KeepAliveInDays="7" />
      <SessionExpiryType>Rolling</SessionExpiryType>
      <SessionExpiryInSeconds>604800</SessionExpiryInSeconds> <!-- 1 week -->
```

What could be still causing this Bad request?

**Comment by pkanher617** [comment]
@leniel as I said in #1091, as MSAL AngularJS is currently locked to MSAL version 0.2.2, it will not have any of the bug fixes or features available in the latest version of the library. Please try using the latest MSAL Angular alpha and see if you experience has improved.

**Comment by leniel** [comment]
@pkanher617 that makes sense... one question: is it possible to use MSAL Angular wrapper with an AngularJS application? Is there any sample?

**Comment by jasonnutter** [comment]
@leniel I don't believe MSAL Angular would work with AngularJS.

**Comment by leniel** [comment]
@jasonnutter thanks... this confirms that the team should move the code to a recent version of Angular.

**Comment by emulic** [comment]
We have the same issue when using oidc-client to authenticate against AAD B2C from an angular spa. Were you able to solve this issue?

**Comment by leniel** [comment]
> We have the same issue when using oidc-client to authenticate against AAD B2C from an angular spa. Were you able to solve this issue?

@emulic not really... from what I know, the team had to move to an updated version of Angular... the app was using 1.6x. I'm not working on this app anymore, so I'm not sure if they got this working while still on the old version.

**Comment by emulic** [comment]
Thanks for answering Leniel. I don't believe it is related to the Angular version. We use Angular 8 and have the same issue. It seems to be an issue in AAD B2C SignIn flow implementation. The same error happens when using "Run user flow" from B2C dashboard in Azure Portal to test the SignIn flow without calling it from our SPA.

**Comment by Prathyusha191** [comment]
I agree with @emulic ,
Ours is a React application and we used https://www.npmjs.com/package/react-azure-adb2c,
and even we are facing the same issue.
we are getting 400 when we leave the page for 4hours or so.
And I feel this issue is with AAD B2C  SignIn flow, and needs a fix

**Comment by salimchemes** [comment]
we are having the same issue, we also tried also with
https://www.npmjs.com/package/angular-auth-oidc-client and got the same problem

I wonder if this is a b2c issue and not a client side

**Comment by flieks** [comment]
I am having the same issue (only in production). Using https://github.com/syncweek-react-aad/react-aad

**Comment by PhineasJiang** [comment]
Why this issue is closed. @sameerag  It has been fixed? I also meet the same problem when using Msal Angular to go to azure Ad b2c page. The login will fail to got a 400 bad request after waiting for some hours.

**Comment by flieks** [comment]
for me i dont know exactly what i did but started working properly.
have the empty auth.html at 
`tokenRefreshUri: window.location.origin + '/auth.html'`
and some other code (more react-aad related)
```return <AzureAD provider={authProvider} forceLogin={true}>
        {
            ({ login, logout, authenticationState, error, accountInfo }) => {
                window.onSignOut = logout

                console.logF("AzureAD accountInfo", accountInfo)
                console.logF("AzureAD authenticationState", authenticationState)
                if(error) {
                    console.logF("AzureAD error", error)
                }

                switch (authenticationState) {
                    case AuthenticationState.Authenticated:
                             if(!accountInfo.jwtAccessToken) {
                                authProvider.getAccessToken() 
                                return null
                             }
                           
                            localStorage.setItem('jwtAccessToken', accountInfo.jwtAccessToken)

                        return  <div style={{ width: '100%' }}>
                            {accountInfo && <AppWithStyles />}
                        </div>```
