### ISSUE TITLE
Iframes auth redirect

### ISSUE THREAD

**Issue by md-swe-hiring** [AzureAD/microsoft-authentication-library-for-js#1169]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: 1.2.0

</code></pre>

## Current behavior

As per the release notes for msal.js 1.2.0 acquire token via redirect is now supported for apps running in Iframes. However it does not work for us. The auth state is left as "in progress" and we do not even find any support for this in the released code. Specifically PR https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/975/files does not seem to be in release 1.2.0.

## Expected behavior

I expect to get a token in the app even when running in Iframe.

**Comment by jasonnutter** [comment]
@md-swe-hiring Using redirect is one scenario that is **not** supported yet. I understand from the release notes why you might think that, so we'll make sure this made clear. cc: @sameerag 

In the mean time, you will need to use one of the other methods inside in iframe. Apologies for the confusion.

**Comment by sameerag** [comment]
The plumbing is there except for a specific use case where `loginRedirect` cannot be called from popups; I can check once and reachout @md-swe-hiring; will publish a sample that clarifies the usage.

The release notes [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-JS-1.2.0#redirect-apis) will be updated as soon as this is ready. Apologies for the delay, we focused on closing all other flows before this.

**Comment by md-swe-hiring** [comment]
Thanks a lot. It would be great with a sample.

**Comment by frejsoya** [comment]
Just to follow up. The release notes, for linking to PRs that are not merged or part of the released code for 1.2.0 is quite confusing.

**Comment by sameerag** [comment]
@frejsoya The code needed is already merged, however we are yet to support some use cases: redirects in popups etc which seem to be a popular use case for Teams users. 

Expected to work in iframes:
`loginPopup`, `acquireTokenPopup` and `acquireTokenSilent`

Future support in iframes:
`loginRedirect` and `acquireTokenRedirect`

**Comment by frejsoya** [comment]
Cool! Thanks. 

FWIW 
I simply can't find any trace of the code 975 in the release, via NPM or any other branch for that matter. Ie. the intercommunication setup between top/child iframe.  Another approach was completed or?

**Comment by frejsoya** [comment]
👍

Just be aware that you link to a pull request in the release notes, the PR
is merged, but not to a branch that exists anymore, and the code is not
part of the release either.

**Comment by sameerag** [comment]
Sorry for the confusion, This isn't merged to dev as we wanted to release the sample with the code. I mistakenly believed it is merged seeing the merged labeling, but it isn't the case. Will release the code and the sample in the first two weeks of Jan.

**Comment by frejsoya** [comment]
Great! Thank you for clearing it up :)

**Comment by mayo589** [comment]
Hi @sameerag ,
any update when we can expect the samples? I am also working on my solution using MSAL in hidden iframe in SharePoint Online :)

**Comment by sameerag** [comment]
Update: #1201 will be used to port these changes to dev instead of #975. Hoping to close with some sample usage this week.

**Comment by mayo589** [comment]
Hello, any updates?

**Comment by sameerag** [comment]
@mayo589 Early next week mostly. This is marked for January and is being tracked.

**Comment by ssvinciak** [comment]
Hello, could you kindly check current status of the issue for me? I've been waiting for fixing this problem for a month. Thanks

**Comment by sameerag** [comment]
Yes! The code is now moved to dev and release will happen this week. Blocked the release as we are working on a sample.

**Comment by sameerag** [comment]
Also, did you happen to try our auth-code alpha branch #1000? That could be a good long term solution for folks wanting to use redirect in iFrames as implicit flow solution we have in place still may be a problem for certain use cases where third party cookies are blocked or for Safari ITP restrictions. This is FYI and we plan to release the msal-browser by the end of March. 

More context on this effort is added in the release notes of the npm package [here](https://www.npmjs.com/package/@azure/msal-browser)

**Comment by frejsoya** [comment]
Thanks for the info. Any updates on the release? We can always write our own hacky solution, but i did not want to duplicate your work :)

**Comment by sameerag** [comment]
@frejsoya Thanks for your patience.
Can you help testing a branch? This solution needs the below conditions as prerequisite to work:

- the parent and iframe apps run `msal js` 
- iframe app allows for messaging from the parent -> ideally this should be working by default
- Some placeholder code in the parent app to help with acknowledging the iframe app's request for parent app's UI

I can share more details/steps to test once we understand this is your app scenario.

**Comment by mayo589** [comment]
@sameerag 
I can also help to test with this one I think. My scenario is that, I hide iframe with MSAL in SharePoint Bottom placeholder. So, I think:
- we can include MSAL js into parent, which is sharepoint online
- messaging to iframe should be working
- we can implement maybe some popups with acknowleding

**Comment by frejsoya** [comment]
Sorry we have not had time to look at this. Do you require testing from us before this can be release or? :)

**Comment by sameerag** [comment]
Okay! We kind of halted the release as this does not solve all use cases, especially safari ITP issues will still persist even with this solution. The above is done as a POC for use cases that work without Safari and ITP restrictions.

We do plan to eventually have a more comprehensive solution to address all scenarios but there is no line of sight on that currently, since it involves a multi-team effort.

If that is alright for your apps, I can share the steps soon, apologies for the delay in reaching out.

**Comment by frejsoya** [comment]
We can live without Safari. Thanks for the feedback, and yes please share steps :)

**Comment by sameerag** [comment]
@frejsoya I am checking in that I did not forget about this. Currently heads down in [msal-node] development and closing on some deadlines there. I should be able to spend some time in the coming weeks on this.

As I would need some help in developing the sample, can you please email me sameera.gajjarapu@microsoft.com and we can kick start there? Once we establish this is working, I will publish the usage of this POC in public space.

**Comment by idri** [comment]
@sameerag Do you have any updates on this feature? When will this be included in an official release (I see PR #1201 is still open)? 

My usecase: I have an Angular SPA with an iframe that needs to performs loginRedirect() to Azure AD B2C login page for Credentials Entry and token retrieval. We don't want to use loginPopup() as this would break our SPA flow. The custom policy is configured to use iframe with "same-origin" (I guess that's fine). Once the login page is displayed in the iframe, user enters credentials and logs-in and access token is provided into iframe and then handed over to the Angular SPA.

Can you please confirm the following:
1. I understand that this feature from PR #1201 will allow the possibility to get the access token into the parent SPA app and use it for accessing protected APIs. 
2. There's no other way of using the msal.js to perform authentication without popup, other than using loginRedirect() in iframe, right?

Thank you.

**Comment by sameerag** [comment]
Apologies for the delay on this. So here is where we landed w.r.t this scenario:

* These scenarios will be available in MSAL JS v2.0
* Currently `MSAL JS Broker` work is in progress;  cc @jasonnutter @tnorling and @pkanher617  are working on the design and dev for this feature
* The above PR is a POC and we think this is a half baked solution and moving to `Broker` support when available would be a more appropriate approach

You can follow our roadmap and we will soon be uploading relevant information soon.
