### ISSUE TITLE
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.

### ISSUE THREAD

**Issue by vaibhavrmore1** [AzureAD/microsoft-authentication-library-for-js#2941]
The issue started occurring after upgrading, msal-browser library from 2.7.0 to 2.10.0
The issue looks similar to [mentioned here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2149).

Reproducing Scenario:
1. User visits the application site and login page is displayed
2. User does nothing and just cancels the tab
3. User revisits the site
4. Instead of redirection page gets stuck and throws the below error in the console. 

`
Auth.js:140 BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
    at t [as constructor] (https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2199109)
    at new t (https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2303388)
    at Function.t.createInteractionInProgressError (https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2304597)
    at t.e.preflightInteractiveRequest (https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2355540)
    at t.<anonymous> (https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2345343)
    at n (https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2188814)
    at Object.next (https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2188118)
    at https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2188052
    at new Promise (<anonymous>)
    at r (https://app.skypointcloud.com/static/js/main.75fef40c.js:1:2187849)`
    
    The issue is reproducible in 2.10.0 version.

**Comment by tnorling** [comment]
@vaibhavrmore1 Sorry for the trouble. This is a known regression in version 2.10.0 and will be fixed in the next release by the PR I just linked. In the meantime you can downgrade to 2.9.0 or use `sessionStorage` to mitigate

**Comment by vaibhavrmore1** [comment]
@tnorling,
It's downgraded as of now to avoid the issue. When can the fix be expected for the issue in the latest version?

**Comment by tnorling** [comment]
@vaibhavrmore1 `msal-browser@2.11.0` has just been released and contains the fix for this issue. Closing, please open a new issue if you have further questions. Thanks!

**Comment by prkhandelwal** [comment]
@tnorling Thanks for the update, but we're still facing this issue after upgrading to `msal-browser@2.11.0`. The issue is not replicated in v2.7.0

**Comment by prkhandelwal** [comment]
@tnorling Thanks for the update, but we're still facing this issue after upgrading to msal-browser@2.11.0. The issue is not replicated in v2.7.0

**Comment by tnorling** [comment]
@prkhandelwal The scenario shared in the original post was fixed in the latest version. Your issue may be different, could you please open a new issue and include your configuration and steps to reproduce. Thanks!

**Comment by prkhandelwal** [comment]
Hey @tnorling , actually @vaibhavrmore1 and I are referring to the same code-base.

**Comment by tnorling** [comment]
@prkhandelwal Nevertheless I'm still going to need more information than what has been provided. Please open a new issue and make sure to fill out one of our provided [issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose) so that our livesite engineer has enough information to debug.

**Comment by SamuelQZQ** [comment]
@tnorling I met the same issue:
```
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
    at BrowserAuthError.AuthError [as constructor] (https://localhost:44335/vendors~main.a449b91f42861068100e.js:237:24)
    at new BrowserAuthError (https://localhost:44335/vendors~main.a449b91f42861068100e.js:6567:28)
    at Function.push../node_modules/@azure/msal-browser/dist/index.es.js.BrowserAuthError.createInteractionInProgressError (https://localhost:44335/vendors~main.a449b91f42861068100e.js:6610:16)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/index.es.js.ClientApplication.preflightInteractiveRequest (https://localhost:44335/vendors~main.a449b91f42861068100e.js:9691:36)
    at PublicClientApplication.<anonymous> (https://localhost:44335/vendors~main.a449b91f42861068100e.js:9235:45)
    at step (https://localhost:44335/vendors~main.a449b91f42861068100e.js:101:23)
    at Object.next (https://localhost:44335/vendors~main.a449b91f42861068100e.js:82:53)
    at https://localhost:44335/vendors~main.a449b91f42861068100e.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (https://localhost:44335/vendors~main.a449b91f42861068100e.js:71:12)
```

Even if I upgrade to 2.11.0, the issue still exists.

**Comment by tnorling** [comment]
Again, just saying something doesn't work isn't enough for us to debug and determine what needs to be fixed. We need actionable reproduction steps so that we can understand if this is a bug in the library or a usage problem. The scenario in the original post was reproduced in the previous version and no longer reproduced in 2.11.0 so if it's still happening there's a piece of information missing. Filling out the issue templates (which this issue has not done) helps us get the information we need to better understand your scenario and assist you faster.
