### ISSUE TITLE
Cannot read property 'B2C' of undefined

### ISSUE THREAD

**Issue by ht89** [AzureAD/microsoft-authentication-library-for-js#301]
Hello everyone, would you please help me with this issue that I have when accessing my production Angular 6 app? Thanks a lot. Here's the details of the issue

ERROR TypeError: Cannot read property 'B2C' of undefined
    at Function.e.DetectAuthorityFromUrl (main.58ad9cf0316c1e1e28d1.js:1)
    at Function.e.CreateInstance (main.58ad9cf0316c1e1e28d1.js:1)
    at e.set [as authority] (main.58ad9cf0316c1e1e28d1.js:1)
    at new e (main.58ad9cf0316c1e1e28d1.js:1)
    at new e (main.58ad9cf0316c1e1e28d1.js:1)
    at main.58ad9cf0316c1e1e28d1.js:1
    at Oo (main.58ad9cf0316c1e1e28d1.js:1)
    at Lo (main.58ad9cf0316c1e1e28d1.js:1)
    at e.get (main.58ad9cf0316c1e1e28d1.js:1)
    at ya (main.58ad9cf0316c1e1e28d1.js:1)

**Comment by rohitnarula7176** [comment]
@ht89 Can you please attach code snippet for your app to show how you are calling msal.

**Comment by spottedmahn** [comment]
Did you wire up msal logging?

**Comment by ht89** [comment]
Hi @rohitnarula7176 , thanks for your reply. Here's my login configuration (keep in mind that the clientID below is not real. I changed it for security purposes):

`private applicationConfig = {
        tenant: 'kellerdruckcloud.onmicrosoft.com',
        clientID: 'abcdf',
        signUpSignInPolicy: 'B2C_1_devapikellercloudSUSIPolicy',
        b2cScopes: ['https://kellerdruckcloud.onmicrosoft.com/devapi/demo.read', 'offline_access']
 };

// Configure the authority for Azure AD B2C
private authority = 'https://login.microsoftonline.com/tfp/' + this.applicationConfig.tenant + '/'
        + this.applicationConfig.signUpSignInPolicy;

private userAgentApplication = new Msal.UserAgentApplication(
        this.applicationConfig.clientID,
        this.authority,
        this.authCallback,
        {
            cacheLocation: 'localStorage',
            redirectUri: environment.authService.redirectUri,
            postLogoutRedirectUri: environment.baseURL
        }
);`

**Comment by ht89** [comment]
Hi @spottedmahn , thanks for your reply. Would you please elaborate your question? Thank you.

**Comment by spottedmahn** [comment]
Hi @ht89 - you can wire up logging of the MSAL library to see what it is doing:

```js
var logger = new Msal.Logger(loggerCallback, { level: Msal.LogLevel.Verbose, correlationId:'12345' }); // level and correlationId are optional parameters.
//Logger has other optional parameters like piiLoggingEnabled which can be assigned as shown aabove. Please refer to the docs to see the full list and their default values.

function loggerCallback(logLevel, message, piiLoggingEnabled) {
	console.log(message);
}

var userAgentApplication = new Msal.UserAgentApplication(applicationConfig.clientID, null, authCallback, { logger: logger, cacheLocation: 'localStorage'}); //logger and cacheLocation are optional parameters.
```
[Source](https://github.com/AzureAD/microsoft-authentication-library-for-js)

**Comment by ht89** [comment]
Hi @spottedmahn , thanks a lot for your replies. I used the latest version of msal which is 0.1.5. It's weird that when running my Angular 6 app locally, it works fine. However, that's not the case when building the app for production and access it locally.

**Comment by spottedmahn** [comment]
Interesting... can you share you build command that doesn't work?

**Comment by ht89** [comment]
Hi @spottedmahn , thanks for your reply. I just use `ng build --prod` to build the app for production. This causes the issue. When using `ng serve`, the issue does not happen.

**Comment by ht89** [comment]
Also, the issue only happens when accessing the production app locally. Thanks

**Comment by spottedmahn** [comment]
>the issue only happens when accessing the production app locally

How are accessing it?  `ng build --prod` only builds and doesn't serve it.

**Comment by spottedmahn** [comment]
- I created a sample using [Angular 5](https://github.com/spottedmahn/Experiments/tree/angular-5/angular6-b2c) with B2C using GitHub and local accounts.  That worked.
- I upgraded that sample to [Angular 6](https://github.com/spottedmahn/Experiments/tree/angular-6/angular6-b2c).  That worked too.

----

- I build it using `npm run build` which equates to `ng build --prod`
- I deployed it to Azure here: https://angular-6-b2c.azurewebsites.net/

---

![angular 6 login](https://user-images.githubusercontent.com/14079228/40132143-f8b8b42a-5909-11e8-9b2c-0cedb0c27379.gif)

**Comment by ht89** [comment]
Hi @spottedmahn , thanks so much for your help. Sorry I could not reply earlier. I use `http-server -p 4200` to serve the production app. It's interesting that your Angular 6 app works with msal. I will need to check other stuff to see what's wrong.

**Comment by ht89** [comment]
Hi @spottedmahn , in your Angular 6 sample, i can see you use the angular version 6.0.2. Therefore, I upgraded angular to that version and now the issue still happens but after inputting my credentials on the login page and clicking the login button. Please take a look at the screenshot. Thank you.
![screenshot from 2018-05-17 11-46-52](https://user-images.githubusercontent.com/11190412/40157324-99962e5e-59c8-11e8-9a5a-0a27ff6fc124.png)

**Comment by ht89** [comment]
Hi @spottedmahn , no worries :) yes the issue can be closed. Thank you.

**Comment by kuncevic** [comment]
Seems like `angular 6.0.3` having the issue when building `--prod`

**Comment by ht89** [comment]
Thanks for sharing your info @kuncevic
