### ISSUE TITLE
Getting "BrowserAuthError: no_cached_authority_error: No cached authority found" error 

### ISSUE THREAD

**Issue by SaviChinnadurai** [AzureAD/microsoft-authentication-library-for-js#3486]
### Core Library

@azure/msal-browser

### Core Library Version

2.13.0

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.2

### Description

We are getting this "no_cached_authority_error" error sometimes especially when the site is kept open in the browser. It starts when the site redirects to login page and though user enters valid login credentials it throws up this error and login fails. Also if the user click on Login button it then throws up "BrowserAuthError: interaction_in_progress: Interaction is currently in progres" error.  User had to close the browser window and open a new window to resolve this issue. Really appreciate any guidance to resolve this problem.

Our stack:
Angular 11
Angular Material 11
@azure/msal-angular  2.0.0-beta.2
@azure/msal-browser 2.13.0

### Error Message

BrowserAuthError: no_cached_authority_error: No cached authority found.
    at e [as constructor] (https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1361485)
    at new e (https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1458628)
    at Function.e.createNoCachedAuthorityError (https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1463217)
    at e.<anonymous> (https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1510258)
    at https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1354882
    at Object.next (https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1354987)
    at https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1353924
    at new D (https://www.site.com/polyfills-es2015.61907dbe52a96d0c7c6e.js:1:17825)
    at Xn (https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1353672)
    at e.t.handleHash (https://www.site.com/main-es2015.0ef41f2e872dd8466e5f.js:1:1509879)

### MSAL Configuration

```javascript
auth: {
      clientId: environment.clientId,
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: environment.RedirectUrl,
      postLogoutRedirectUri: environment.RedirectUrl,
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    }
```

### Relevant Code Snippets

```javascript
Not available
```

### Reproduction Steps

Occurs randomly

### Expected Behavior

Should acquire token successfully.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

Not worked before

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@SaviChinnadurai The `no_cached_authority_error` error happens if there isn't a cache entry for the authority for request. This can potentially happen if the temporary cache used by MSAL is cleared. In MSAL.js v2, all temporary cache values are stored in `sessionStorage` (token storage is based on the `cache.cacheLocation` setting). Can you please try debugging to figure out if there is a session storage entry for the authority value when this error is thrown?

As a mitigation, can you try setting `storeAuthStateInCookie` to `true` for all users, and see if that resolves the issue?

**Comment by SaviChinnadurai** [comment]
Thanks jason. I have implemented your mitigation suggestion  to set `storeAuthStateInCookie ` to true for now. Hopefully it will resolve the issue.

**Comment by jasonnutter** [comment]
@SaviChinnadurai Great, let me know how it goes. We've heard separate reports of this error, so we'll investigate further.

**Comment by jasonnutter** [comment]
@SaviChinnadurai I've been unable to reproduce this issue.

> We are getting this "no_cached_authority_error" error sometimes especially when the site is kept open in the browser. It starts when the site redirects to login page and though user enters valid login credentials it throws up this error and login fails.

Can you please clarify for how long the site is kept open? And on which site is the browser left open, your app or the login page?

**Comment by jasonnutter** [comment]
Also, please verify that this issue still exists with the latest version of MSAL Broser (2.14.0).

**Comment by SaviChinnadurai** [comment]
> Can you please clarify for how long the site is kept open? And on which site is the browser left open, your app or the login page?

Unfortunately I too don't have the fixed steps to reproduce this error. As I mentioned it happens randomly sometimes. I have deployed the mitigation change to our dev site and going to test it for next few days to confirm if the fix has resolved the issue.
Yes, I have upgraded both msal/angular (2.0.0-beta.4) and msal/browser (2.14.0) to latest versions.

Our site has a set of public pages (requires no authentication) and members only secured pages which will prompt login redirect. My guess is if the site window is left in members only page and then accessed after few days time msal redirects site to login page but on return it is throwing this "no_cached_authority_error" error.  Again this is my hunch.

Can your mitigation fix (storeAuthStateInCookie to true) be used permanently if it resolves this issue?   Also Is it okay to call a protectedResource api in app.component?  

Thanks again.
