### ISSUE TITLE
ClientAuthError: multiple_matching_tokens error when cache kept more than 2 users

### ISSUE THREAD

**Issue by hastudillo** [AzureAD/microsoft-authentication-library-for-js#4486]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.5.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When using a "singleton instance of confidentialClientApplication" we have found the "case that in cache there is two accounts, third account try to make first time a OBO and we get multiple_matching_tokens error."

Originally posted by @CrazyBaran in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4158#issuecomment-944152234

With my team, we have found exactly the same issue... Maybe important to say that the cache has exactly 12 items when it happens.

@sameerag We are wondering if the potential solution is still alive, for it seems recently to be more or less without activity: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4081

And by the way, the only quick workaround we've found so far is to always clear the cache XD
Have you by chance found another one @CrazyBaran ?

### MSAL Configuration

```javascript
const config: Configuration = {
  auth: {
    clientId: 'our clientId',
    authority: 'https://login.microsoftonline.com/our tenantId',
    clientSecret: 'our clientSecret',
  },
};
this.cca = new ConfidentialClientApplication(config);
```

### Relevant Code Snippets

```javascript
const cachedAccount: AccountInfo = await this.cca
      .getTokenCache()
      .getAccountByLocalId((jwtDecode(token) as UserPayload).oid);
    if (cachedAccount?.localAccountId) {
      return await this.cca.acquireTokenSilent({
        account: cachedAccount,
        scopes: ['https://vault.azure.net/.default'],
        authority: 'https://login.microsoftonline.com/our tenantId',
      });
    }
	return this.cca.acquireTokenOnBehalfOf({
      oboAssertion: token.split(' ').pop(),
      scopes,
      authority: 'https://login.microsoftonline.com/our tenantId',
    });
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@hastudillo Thanks for raising this. Can you confirm the potential fix works? And yes #4081 is still tracked, just delayed as we had some issues with E2E test suite and could not get to it sooner.

It helps if you can also confirm the fix works on your end.

**Comment by hastudillo** [comment]
@sameerag Thank you for your answer. We will test the potential fix in an environment. We will share with you whether the bug is reproduced or not in a couple of days.

**Comment by hastudillo** [comment]
Same error reproduced with the fix. Here below the status of the cache before the error:
```
  {
    cacheHasChanged: true,
    storage: A {
      clientId: 'OUR_CLIENT_ID',
      cryptoImpl: m { pkceGenerator: y {} },
      cache: {
        'authority-metadata-OUR_CLIENT_ID-login.windows.net': [AuthorityMetadataEntity],
        'FIRST_USER_LOGGED.OUR_TENANT_ID-login.windows.net-OUR_TENANT_ID': [AccountEntity],
        'FIRST_USER_LOGGED.OUR_TENANT_ID-login.windows.net-idtoken-OUR_CLIENT_ID-OUR_TENANT_ID---': [IdTokenEntity],
        'FIRST_USER_LOGGED.OUR_TENANT_ID-login.windows.net-refreshtoken-OUR_CLIENT_ID----': [RefreshTokenEntity],
        'SECOND_USER_LOGGED.OUR_TENANT_ID-login.windows.net-OUR_TENANT_ID': [AccountEntity],
        'SECOND_USER_LOGGED.OUR_TENANT_ID-login.windows.net-idtoken-OUR_CLIENT_ID-OUR_TENANT_ID---': [IdTokenEntity],
        'SECOND_USER_LOGGED.OUR_TENANT_ID-login.windows.net-refreshtoken-OUR_CLIENT_ID----': [RefreshTokenEntity],
        'SECOND_USER_LOGGED.OUR_TENANT_ID-login.windows.net-accesstoken-OUR_CLIENT_ID-OUR_TENANT_ID-https://vault.azure.net/user_impersonation https://vault.azure.net/.default--': [AccessTokenEntity],
        'FIRST_USER_LOGGED.OUR_TENANT_ID-login.windows.net-accesstoken-OUR_CLIENT_ID-OUR_TENANT_ID-https://vault.azure.net/user_impersonation https://vault.azure.net/.default--': [AccessTokenEntity],
        'server-telemetry-OUR_CLIENT_ID': [ServerTelemetryEntity]
      },
      changeEmitters: [ [Function: bound handleChangeEvent] ],
      logger: Logger {
        level: 2,
        localCallback: [Function: loggerCallback],
        piiLoggingEnabled: false,
        correlationId: '',
        packageName: '@azure/msal-node',
        packageVersion: '1.5.0'
      }
    },
    logger: Logger {
      level: 2,
      localCallback: [Function: loggerCallback],
      piiLoggingEnabled: false,
      correlationId: '',
      packageName: '@azure/msal-node',
      packageVersion: '1.5.0'
    }
  }
```
When the third account tries to obtain a token for the Key Vault OBO (explicitly), then:
```
ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account.
```
We noticed that that, this time, the cache has 10 items when it happens. So it seems to be more important the number of accounts whose tokens are cached than the number of entries.

**Comment by sameerag** [comment]
@hastudillo  Thanks for the details. 

We need to reproduce this on our end to see what is happening. Can you please confirm a few things before we do that:
* The third account is unique?
* Did you try clearing only specific cache entries (agree this will ne hacky) and test adding the new account and see if it passes? This is mostly to test the theory I see put forward in the issue (12 entries created before the issue pops up)?

Also can you please enable logging and let us know the exact point of failure? I still think it is match issue and not cache capacity.

cc @hectormmg

**Comment by coder-pm** [comment]
I was working on that few months ago. Found out that `multiple_matching_tokens` is thrown due to that part of the code: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/60e2cfc0e9daa3c24e994617b4ac42aef6880b74/lib/msal-common/src/client/OnBehalfOfClient.ts#L107

`accessTokenFilter` is the same for all accounts, there is nothing "account specific" during generation of that token. Our workaround was to completely disable the cache.

**Comment by sameerag** [comment]
Actually this makes sense. I however remember we used to do `uid.utid` filtering before fetching account specific access tokens. I will take a look at this bug. 

Since the `accessToken` key is defined as `Key Example: uid.utid-login.microsoftonline.com-accesstoken-clientId-contoso.com-user.read` as below:  https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/60e2cfc0e9daa3c24e994617b4ac42aef6880b74/lib/msal-common/src/cache/entities/AccessTokenEntity.ts#L20 
ideally we should be able to filter this with account data added.

**Comment by sameerag** [comment]
If this is OBO, we should have account info. It is only for client-credential flow that we completely discard `accountInfo` since there is no user info.

**Comment by hastudillo** [comment]
@sameerag Thank you for your answer.
* I can confirm that the third account is unique.
* We haven't tested clearing only specific cache entries.
* As mentioned above (02/08) we noticed that the cache had 10 items when the error was reproduced. So it seems to be more important the number of accounts whose tokens are cached than the number of entries.
Tested with the following `package.json`:
```
  "scripts": {
    "postinstall": "cd node_modules/@azure/msal-node; npm install; npm run build",
...
  "dependencies": {
    "@azure/msal-node": "https://gitpkg.now.sh/AzureAD/microsoft-authentication-library-for-js/lib/msal-node?fix-inmemory-cache",
```
As the time for always acquiring a new token is just a matter of some millis. we are not planing to deploy again in order to reproduce one more time the error (but you are right, it have been a good idea to enable logging at info level!). If we get chance to do so, for sure we will share the logs.  
Still, of course, we are still interested in the issue, we'll remain attentive to the matter.

**Comment by sameerag** [comment]
@hastudillo Thanks for the data. We think this is a bug in access token filtering, which should include account matching. I am marking this as a bug and will follow up with a PR.

**Comment by andrew-hwahin** [comment]
> Our workaround was to completely disable the cache.

Hi, may I know how to completely disable the cache for a temporary fix?

cc @coder-pm

**Comment by coder-pm** [comment]
@andrew-hwahin don't provide any `cachePlugin` and it should use `in-memory` cache by default. There is no issue there.

**Comment by andrew-hwahin** [comment]
@coder-pm Thanks for the prompt response, but I'm facing the same issue even though I did not provide any cache to it. 🤔

**Comment by dillonbailey** [comment]
@sameerag we're encountering the same bug on our project - disabling the cache is not a solution for us. Any updates would be great!

**Comment by andrew-hwahin** [comment]
Is there any other temporary fix I could implement to avoid this bug?

**Comment by sameerag** [comment]
We are adding an enhancement in OBO and will be pushing a PR soon that should potentially resolve this issue. Please watch this space for the updates, I am tracking this issue.

**Comment by dillonbailey** [comment]
@sameerag thank you! As this is blocking a client project would it be possible for us to share an ETA on the fix?

**Comment by dillonbailey** [comment]
> @sameerag thank you! As this is blocking a client project would it be possible for us to share an ETA on the fix?

Sorry to bump, we're just doing our sprint planning/refinement and are hoping to share an update with the team.

**Comment by sameerag** [comment]
#4691 is a work in progress, ETA 4/22

**Comment by dillonbailey** [comment]
Thanks @sameerag - any new updates on targeted release?

**Comment by dillonbailey** [comment]
@tnorling @sameerag any updates here?

**Comment by andrew-hwahin** [comment]
hope this issue will be resolved asap as it affects production 🙏🙇‍♂️
we had to keep restarting the application server to overcome the error

**Comment by sameerag** [comment]
@dillonbailey @andrew-hwahin We have released a new `msal-node` version that should fix this. Can you please try and let us know if it solves your issue?

> notes from the release:

🎉@azure/msal-node@v1.10.0 has been released which incorporates this pull request.🎉

Handy links:

[Release Notes](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-node-v1.10.0)
[Official NPM Release](https://www.npmjs.com/package/@azure/msal-node/v/1.10.0)

**Comment by andrew-hwahin** [comment]
> @dillonbailey @andrew-hwahin We have released a new `msal-node` version that should fix this. Can you please try and let us know if it solves your issue?

@sameerag thanks to you and your team for fixing the bug, I will test it out and report back if the issue still persists. 🙏🙇‍♂️

**Comment by andrew-hwahin** [comment]
@sameerag I got HTTP status code 401 after upgrading my @azure/msal-node from 1.8.0 to 1.10.0, I've read the release notes from 1.9.0, 1.9.1 and 1.10.0, but doesn't find any instruction which I needed to make in order to upgrade.

**Comment by toddarmstrong** [comment]
Hi @sameerag 

I am a colleague of @dillonbailey and am taking over here.
We have updated msal-node to 1.10.0 but are still experiencing this issue.

What information do you need from us to further look into this?
