### ISSUE TITLE
Problem with msal-browser v2.32.2 on safari

### ISSUE THREAD

**Issue by kbartyzel** [AzureAD/microsoft-authentication-library-for-js#5548]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

"@azure/msal-react": "1.5.1"

### Public or Confidential Client?

Public

### Description

We have  exceptions
* Unhandled Promise Rejection: SyntaxError: Invalid regular expression: invalid group specifier name
* SyntaxError: Invalid regular expression: invalid group specifier name
and few others after updating to the new package. Yesterday everything was working.

Previously working version was
"@azure/msal-common" : "9.0.1",
"@azure/msal-browser": "2.32.1",
"@azure/msal-react": "1.5.1",

### MSAL Configuration

```javascript
confidential - but correct, works for months
```

### Relevant Code Snippets

```javascript
The token is valid, everything is configured correctly
```

### Reproduction Steps

Open a page
Start to log in
After login, redirect back to the original page, we have an exception

### Expected Behavior

Token is valid, everything is configured correctly

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Regression

@azure/msal-browser": "2.32.1

### Source

Internal (Microsoft)

**Comment by kbartyzel** [comment]
![image](https://user-images.githubusercontent.com/61357068/211532726-09d52c39-55d9-478f-a380-7f0b65e2b0de.png)

**Comment by SimoNDeviL** [comment]
From version 
"@azure/msal-common" : "9.0.2", 
problems begins on Chrome, Edge, Firefox and Safari.

**Comment by submarines-and** [comment]
Same issue for us.

Could it be this commit?
https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/29701fa413206b07bc30178f22ec027d9bc3e8d6

<img width="827" alt="image" src="https://user-images.githubusercontent.com/3114694/211537173-5ce4f6cf-0ce8-4e72-9cd9-acac50677617.png">


As I recall, Safari does not have support for lookbehind.

Sorry if I am way off, take this with a grain of salt :)

**Comment by hectormmg** [comment]
Thanks for raising the issue @kbartyzel . We'll look into it and provide updates here. For now, please downgrade to 2.32.1 if that's possible.

**Comment by SimonGolms** [comment]
Just a simple downgrade to the previous versions of `@azure/msal-browser@2.32.1` and `@azure/msal-react@1.5.1` will not work, because the dependency `@azure/msal-common` is not specified as a strict version here:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4ba6eb3fa115d61c96bac0ca9eb407199b9a8b93/lib/msal-browser/package.json#L92-L94

So even with a new install, the latest (and corrupt) version of `@azure/msal-common@9.0.2` will be installed, because it is compatible according to semver specification.

With `npm`, I fixed it with the [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) configuration in my `package.json`

```json
{
  "dependencies": {
    "@azure/msal-browser": "2.32.1",
    "@azure/msal-react": "1.5.1",
  },
  "overrides": {
    "@azure/msal-common": "9.0.1"
  }
}
```

**Comment by Webbwhite98** [comment]
> Just a simple downgrade to the previous versions of `@azure/msal-browser@2.32.1` and `@azure/msal-react@1.5.1` will not work, because the dependency `@azure/msal-common` is not specified as a strict version here:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4ba6eb3fa115d61c96bac0ca9eb407199b9a8b93/lib/msal-browser/package.json#L92-L94
> 
> So even with a new install, the latest (and corrupt) version of `@azure/msal-common@9.0.2` will be installed, because it is compatible according to semver specification.
> 
> With `npm`, I fixed it with the [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) configuration in my `package.json`
> 
> ```json
> {
>   "dependencies": {
>     "@azure/msal-browser": "2.32.1",
>     "@azure/msal-react": "1.5.1",
>   },
>   "overrides": {
>     "@azure/msal-common": "9.0.1"
>   }
> }
> ```

This worked for me, I also had to add @azure/msal-common": "9.0.1" as a dependency

**Comment by mkosir** [comment]
> Just a simple downgrade to the previous versions of `@azure/msal-browser@2.32.1` and `@azure/msal-react@1.5.1` will not work, because the dependency `@azure/msal-common` is not specified as a strict version here:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4ba6eb3fa115d61c96bac0ca9eb407199b9a8b93/lib/msal-browser/package.json#L92-L94
> 
> So even with a new install, the latest (and corrupt) version of `@azure/msal-common@9.0.2` will be installed, because it is compatible according to semver specification.

Thanks for pointing this out, this is really useful info 🙇‍♂️
Initially we did a rollback of `@azure/msal-browser` (without overrides config) and the error still persisted.

I think the dependency `@azure/msal-common` should be fixed, to prevent this kind of issues in the future (as also other related dependencies). Otherwise results can be messy for devs since it depends "when" you install MSAL package.

**Comment by aso1datov** [comment]
If you are using `yarn` use `resolutions` instead.

```json
"dependencies": {
    "@azure/msal-browser": "2.32.1",
    "@azure/msal-common": "9.0.1",
    "@azure/msal-react": "1.5.1",
}
"resolutions": {
    "@azure/msal-common": "9.0.1"
 }
  ```
