### ISSUE TITLE
Logout for a Specific App Without Affecting Other Apps Under the Organization

### ISSUE THREAD

**Issue by Edgarb-Claims-Conf** [AzureAD/microsoft-authentication-library-for-js#8112]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

Hi,

We are using Outlook, SharePoint, Entra, and a custom application built with MSAL authentication.

I’m trying to find a way to log out a user **only from our custom application**, without logging them out from other apps. Currently, when a logout happens in our app, it also logs the user out from all other connected apps under the same organization.

According to the MSAL documentation, all apps under the same organization share the same SSO session. When that session is removed during logout, all other apps using it are also affected.

So far, I haven’t found a way to perform a full logout only for a specific app.
Could you please confirm if there’s any method or best practice to achieve app-specific logout without affecting the global SSO session?

(Note: A local logout — clearing local storage or cache — is not an acceptable solution in our case.)

Thank you in advance.

**Comment by tnorling** [comment]
>Could you please confirm if there’s any method or best practice to achieve app-specific logout without affecting the global SSO session?
> (Note: A local logout — clearing local storage or cache — is not an acceptable solution in our case.)

Can you tell me more about why clearing local cache is not acceptable? The short answer is no, the service does not keep track of which apps have signed in or out, it keeps only one cookie per user which is shared across apps to provide SSO. Clearing the local cache is the only way to achieve single app "logout"

**Comment by Edgarb-Claims-Conf** [comment]
Removing the local cache is not an acceptable solution because it doesn’t fully log the user out. After this type of logout, the user can still log in without completing 2FA.
Currently, I’ve implemented a local logout (by clearing the cache) and modified the login flow to force a login prompt. This ensures that the user always sees the login page and 2FA after a local logout. However, in this case, I lose the ability to access the application without 2FA if the user is already logged in to our other applications.

```
await instance.loginRedirect({
    scopes: loginRequest.scopes,
    prompt: "login",
});
```

**Comment by tnorling** [comment]
You're essentially asking to have SSO in some scenarios and no SSO in others. These requirements contradict each other, you may need to re-evaluate. Note that while setting the prompt to login does force a re-auth it should **not** be considered a security gate, it is trivial for any user to remove the prompt parameter from the url in which case they would be signed in using SSO. It's still not clear to me why you need to force a re-auth in just a single app unless it's to switch users, in which case I would suggest changing your logic from a logout to a switch user behavior. But in any case I would strongly recommend reframing your requirements to accept the use of SSO, when available.

**Comment by Edgarb-Claims-Conf** [comment]
You’re right.
Implementing a full logout from one application that also affects other applications led me to a logical contradiction — something I only realized recently, and you noticed it right away.
We’ll review the logic and take your advice into account.
Thank you.
