### ISSUE TITLE
ADFS Support?

### ISSUE THREAD

**Issue by Only1MrAnderson** [AzureAD/microsoft-authentication-library-for-js#99]
Any plan to add ADFS support as the.net library seems to be working on it.?

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/143

**Comment by mitch-b** [comment]
Agreed - it would be nice to move to MSAL from ADAL - with ADFS support being the only missing feature for me.

**Comment by glatzert** [comment]
I second this idea.
Unfortunately, ADFS 2016 cannot support JavaScript at this time, because they lack CORS-Features - therefore you cannot read config data or key-material from client-based js.
It would be nice, if the MSAL Team would engage the ADFS-Team with that Problem.

**Comment by ajtowf** [comment]
Doesn't work (yet) with ADFS 2019 either even if cors is supported, msal says: "ERROR Error: InvalidAuthorityType" when providing an adfs url instead of aad b2b. Just use ADAL.js for now with ADFS.

**Comment by ajtowf** [comment]
Works like a charm using [oidc-client.js](https://github.com/IdentityModel/oidc-client-js) with ADFS 2019 with the dropped "resource" requirement and CORS support.

**Comment by BatmanAMA** [comment]
@ajtowf - do you have a working sample? I'm beating my head against the wall and can't find any examples out there that work in .net core 2.x for using openid against ADFS

**Comment by sameerag** [comment]
@BatmanAMA  @Only1MrAnderson We are testing our latest MSAL JS against this and will update the documentation on ADFS supportability based on the same. Please expect this to be after our current release though.

**Comment by sameerag** [comment]
@negoe can you please follow up on the ADFS support for MSALs? We do know that we do not support the endpoint directly, Clear documentation will help folks who come to this route.

**Comment by rossbuggins** [comment]
@sameerag this is something that would be really useful, teams report that all is working with our .net clients, just the js that its a problem with still.

**Comment by LastTribunal** [comment]
@DarylThayil well, its the end of September, whats the word on MSAL for ADFS???
I really would like to ditch my ADAL JS,, which should be sent back to hell where it came from

**Comment by sameerag** [comment]
@LastTribunal  I have done some digging on this and looks like there is more dev work needed to ensure ADFS 2019 is working in MSAL JS. Our initial assumption was that it is more of guidance issue than dev work, which is not true. Most of this work is was heavily contributed by ADFS team on other MSALs and I have started getting together the details to have this supported in MSAL JS. 

Unfortunately this may not be finished in September, but I will keep updating the progress here.

**Comment by LastTribunal** [comment]
@sameerag thanks for the update.  I really hope I can get my hands on it soon, i have a hybrid app that works both with Azure AD and ADFS, using ADAL for angular.  There are many issues that are making my app almost unusable..

**Comment by LastTribunal** [comment]
@sameerag  any update on the ETA?

**Comment by sameerag** [comment]
Not taken up yet as we are closing a major release, unfortunately,  but it is in my list for October. Will update here soon.

**Comment by LastTribunal** [comment]
@sameerag update?

**Comment by sameerag** [comment]
@LastTribunal Here is what I gathered so far on ADFS as this thread already mentions above: 
- OnPrem ADFS is not yet supported and may not be for a while
- ADFS 2019 should be supported out of the box. 

In this context, I fixed the bug that was throwing the "ERROR Error: InvalidAuthorityType" in `msal js`. Can you please try checking with the latest version of msal : `msal-1.2.0-beta.3` and we can take it forward as it comes?

**Comment by LastTribunal** [comment]
@sameerag, I dont get it.  If msal with adfs is not supported, what is the purpose of testing for this error?
Are you saying that msal should work with adfs 2019 by default?

Can you clarify??

**Comment by sameerag** [comment]
Yes. Msal with ADFS 2019 should work out of the box.

**Comment by LastTribunal** [comment]
do you have a demo msal angular app that i can test against ADFS?

**Comment by rossbuggins** [comment]
Just note, from what I understand, the js library is still not supported for adfs, only the .net library

**Comment by sameerag** [comment]
@LastTribunal Can you please try this using `msal-core` [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/VanillaJSTestApp) substituting the authority with an ADFS 2019 one? Currently we are working on upgrading angular to `msal-core` and currently do not have an available sample.

`msal` latest `beta` version in npm is the recommended version.

**Comment by LastTribunal** [comment]
**@sameerag you guys need to come up with an MSAL Angular implementation and demo app that showcases interfacing with both AAD and ADFS ASAP**  No one cares about MSAL otherwise... what problem does it solve as of right now that ADAL doesnt? The only sick patient is ADALJS/ADALAngular with near fatal symptoms when interfacing with ADFS.  I hope the powers at MS are reading this.

**Comment by sameerag** [comment]
@LastTribunal We are working on Angular release already, please check the project board [angular](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/3) for the progress. We are also working on samples improvements the remaining part of the year. We will follow up with an ADFS 2019 sample once Angular is available.

`msal js` adds support for v2 endpoints, combines support for school, work accounts, B2C etc, more details on this [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview). In `msal js` we also enhanced the API interface and new features which are not present in `adal js`.

The request to try `msal-core` meanwhile is to unblock those set of people who are already using `msal-angular` with custom improvements on the `msal-core`. Hope this clarifies the strategy.

Please note that ADFS on prem is not supported and we do not have line of sight on when that would be supported from microsoft client libraries.

**Comment by marisaoliva** [comment]
Hello:

I've seen that the version 1.2.0 support adfs, but only url microsoft? ¿Is possible use a url adfs private and use Msal?

I try do this but I've a error why the library try to redirect a url that it not the mine

 https://login.microsoftonline.com/common/discovery/instance?api-version=1.0&authorization_endpoint=https://****.**********.com/adfs/oauth2/v2.0/authorize 400 (Bad Request)

**Comment by sameerag** [comment]
Hi @marisaoliva We would need some time to address this as this would need some significant changes in our `authority` code which determines the end point to call for token acquisition. I am tagging this as a `feature request` and we will update the roadmap when we can invest on this.

**Comment by krytical** [comment]
Hi,

Just wondering if there is any update for MSAL and on-premise ADFS? We have a React application that would need ADFS access tokens and we got that working using react-adal, however, we're switching to MSAL as ADAL is not supported anymore.

Thanks!

**Comment by gaelian** [comment]
I'd also like to pile on this one. Considering that MSAL.NET supports direct connections to on-prem AD FS 2019+ (with some minor tweaking of generated JWTs, it turns out) I had more or less assumed that MSAL.js would also have similar support, until reading this issue. My colleagues and I would be very keen to see this becoming a reality so that we have similar approaches available for SPAs.

**Comment by LastTribunal** [comment]
I've been waiting for support from this so called MSAL team, all I got was empty promises and excuses.  Wasted my time

**Comment by jasonnutter** [comment]
Update: We expect to add support for ADFS 2019 in 1.4.0. Follow the above pull request for more. Sorry this took so long, appreciate the patience!
